export const USERS_TWEETS = [
  {
    name: 'Jeramie',
    username: 'Koss',
    tweet:
      'Voluptatem hic ab reprehenderit tempora necessitatibus doloremque dolore. Itaque quia in voluptatum sint non qui maxime nesciunt vero. Ut cupiditate similique eius odio ut. Quaerat corporis ipsa maxime consequuntur est explicabo. Expedita id unde id distinctio et. Repudiandae nihil rerum consequatur facilis.',
    comments: 12,
    retweets: 15,
    likes: 34,
    verified: Boolean(1),
    promoted: Boolean(1),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1178.jpg',
  },
  {
    name: 'Sarina',
    username: 'Hayes',
    tweet:
      'Ullam et earum consequatur velit occaecati corrupti a. Non vero non ea fugit perferendis similique illo excepturi. Voluptas nostrum eos et autem sapiente maiores dolorum.',
    comments: 16,
    retweets: 29,
    likes: 74,
    verified: Boolean(0),
    promoted: Boolean(0),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/597.jpg',
  },
  {
    name: 'Vilma',
    username: 'Kirlin',
    tweet:
      'Quod rerum eos mollitia. Quia culpa dolores animi in quaerat pariatur commodi autem assumenda. Enim possimus accusantium quae et. Sequi et quo natus et voluptas qui et sit.',
    comments: 36,
    retweets: 98,
    likes: 94,
    verified: Boolean(1),
    promoted: Boolean(1),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/544.jpg',
  },
  {
    name: 'Mathias',
    username: 'Gorczany',
    tweet:
      'Iusto et non sed minima rerum debitis minus magni officiis. Pariatur qui est quo vero cum exercitationem id et. Nulla omnis quos odio ut esse cumque praesentium nihil cum.',
    comments: 31,
    retweets: 59,
    likes: 73,
    verified: Boolean(0),
    promoted: Boolean(0),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1249.jpg',
  },
  {
    name: 'Barney',
    username: 'Orn',
    tweet: 'Dolores et omnis sapiente et quibusdam. Explicabo cupiditate corrupti est sunt aut.',
    comments: 100,
    retweets: 7,
    likes: 90,
    verified: Boolean(1),
    promoted: Boolean(1),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/389.jpg',
  },
  {
    name: 'Alexa',
    username: 'Gerlach',
    tweet:
      'Ab voluptates possimus assumenda accusamus. Exercitationem inventore sunt aspernatur cupiditate dolores aspernatur voluptas a. Aliquid consequuntur ea ea.',
    comments: 99,
    retweets: 92,
    likes: 54,
    verified: Boolean(1),
    promoted: Boolean(1),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/858.jpg',
  },
  {
    name: 'Emmalee',
    username: 'Ward',
    tweet:
      'Quia optio ut reprehenderit eum quis veritatis quo quaerat. Possimus dolor et quod voluptates. Aut amet soluta aut. Sed vero qui. Quis ut aut et vitae vero animi reprehenderit distinctio. Quis ut veritatis exercitationem quisquam voluptatem beatae dolor vel.',
    comments: 5,
    retweets: 87,
    likes: 37,
    verified: Boolean(0),
    promoted: Boolean(0),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/863.jpg',
  },
  {
    name: 'Tatum',
    username: 'Heidenreich',
    tweet:
      'Quidem corrupti aut laboriosam. Omnis voluptates distinctio autem ut temporibus consequatur ea dignissimos. Dolorem nihil occaecati nihil molestias sunt eaque.',
    comments: 8,
    retweets: 2,
    likes: 44,
    verified: Boolean(0),
    promoted: Boolean(0),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1239.jpg',
  },
  {
    name: 'Alf',
    username: 'Daniel',
    tweet:
      'Repellendus amet totam. Ipsam ipsam ipsa ab. Culpa accusamus sapiente velit unde ratione. Cumque beatae distinctio est animi et.',
    comments: 89,
    retweets: 12,
    likes: 30,
    verified: Boolean(0),
    promoted: Boolean(0),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/10.jpg',
  },
  {
    name: 'Arne',
    username: 'Hagenes',
    tweet: 'Sequi quisquam ducimus quos ex. Ducimus facilis autem quis quo ducimus ipsum dolores.',
    comments: 44,
    retweets: 90,
    likes: 18,
    verified: Boolean(0),
    promoted: Boolean(0),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1185.jpg',
  },
  {
    name: 'Ryann',
    username: 'Frami',
    tweet:
      'A velit culpa distinctio inventore exercitationem assumenda adipisci occaecati eum. Deleniti non ipsum repellat alias sunt cum ipsa. Eveniet non qui eveniet temporibus repudiandae minima. Commodi fugit vitae vel.',
    comments: 43,
    retweets: 72,
    likes: 91,
    verified: Boolean(0),
    promoted: Boolean(0),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/875.jpg',
  },
  {
    name: 'Renee',
    username: 'Waelchi',
    tweet:
      'Quia deserunt distinctio voluptates dolorum voluptatum cum. Odio odio pariatur similique magni assumenda recusandae magnam est. Consectetur aut error eos.',
    comments: 95,
    retweets: 48,
    likes: 46,
    verified: Boolean(1),
    promoted: Boolean(1),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/267.jpg',
  },
  {
    name: 'Donavon',
    username: 'Dach',
    tweet:
      'Quasi id nam. Consequuntur id quam consequatur nulla. Sint adipisci et facere quae consectetur officia et aut. Voluptates ad deleniti et commodi error dolorem quos.',
    comments: 96,
    retweets: 50,
    likes: 56,
    verified: Boolean(0),
    promoted: Boolean(0),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/556.jpg',
  },
  {
    name: 'Clark',
    username: 'Bode',
    tweet:
      'Suscipit est architecto non reiciendis hic et iusto. Architecto eaque deleniti nam corrupti officiis. Delectus rerum nihil cum illo aut nemo. Omnis voluptates dicta tempora. Architecto vel maiores nesciunt iure dolor officia autem quia.',
    comments: 11,
    retweets: 89,
    likes: 90,
    verified: Boolean(1),
    promoted: Boolean(1),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/985.jpg',
  },
  {
    name: 'Lambert',
    username: 'Murphy',
    tweet:
      'Nostrum architecto vel vero adipisci earum voluptas omnis. Laboriosam ipsam odio nostrum ipsum eius minima amet nihil. Perferendis magni deserunt fuga. Hic nesciunt est aut velit eveniet. Sed quia libero. Sequi quam voluptatem nihil nesciunt.',
    comments: 46,
    retweets: 85,
    likes: 79,
    verified: Boolean(1),
    promoted: Boolean(1),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/600.jpg',
  },
  {
    name: 'Caitlyn',
    username: 'Stark',
    tweet:
      'Eum ullam aperiam et possimus ut tenetur culpa ipsa. Quis aut repellendus enim fugiat voluptate voluptates nemo rerum. Vel voluptatum necessitatibus. Qui ut occaecati. Non nemo reiciendis eos eum placeat laudantium exercitationem ratione. Et dolorum ipsam veniam quis.',
    comments: 68,
    retweets: 28,
    likes: 30,
    verified: Boolean(0),
    promoted: Boolean(0),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/468.jpg',
  },
  {
    name: 'Daryl',
    username: 'Kuvalis',
    tweet: 'Ipsum reprehenderit suscipit libero. Ut unde aliquid quia hic nihil et et et.',
    comments: 13,
    retweets: 41,
    likes: 23,
    verified: Boolean(0),
    promoted: Boolean(0),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/566.jpg',
  },
  {
    name: 'Marcia',
    username: 'Goyette',
    tweet:
      'Incidunt rerum molestiae non non sed et. Dolor similique et autem et quis dolores ut quam. Sint reprehenderit eos voluptas est vel. Magnam neque quia. Sed dolores possimus.',
    comments: 33,
    retweets: 38,
    likes: 55,
    verified: Boolean(1),
    promoted: Boolean(1),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/961.jpg',
  },
  {
    name: 'Zander',
    username: 'Huels',
    tweet:
      'Sit iure cum in. Sunt quibusdam vitae id id et nostrum earum. Officiis quia quidem fugit similique qui. Quae nam doloremque.',
    comments: 69,
    retweets: 6,
    likes: 81,
    verified: Boolean(1),
    promoted: Boolean(1),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/683.jpg',
  },
  {
    name: 'Karolann',
    username: 'Wolff',
    tweet:
      'Perspiciatis laborum eius aut labore nam sapiente quo. Vitae at sed. Dolorem quaerat et consequatur. Et accusantium harum ipsam quos. Ut impedit hic qui sunt quia incidunt consequatur soluta. Vitae omnis et ea optio veniam.',
    comments: 22,
    retweets: 42,
    likes: 81,
    verified: Boolean(1),
    promoted: Boolean(1),
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/258.jpg',
  },
];

export const USERS_TO_FOLLOW = [
  {
    name: 'Maiya',
    username: 'Lynch',
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/440.jpg',
    follower: Boolean(1),
    following: Boolean(0),
    verified: Boolean(1),
    promoted: Boolean(1),
  },
  {
    name: 'Coralie',
    username: 'Krajcik',
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/18.jpg',
    follower: Boolean(1),
    following: Boolean(0),
    verified: Boolean(0),
    promoted: Boolean(1),
  },
  {
    name: 'Alison',
    username: 'Champlin',
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/998.jpg',
    follower: Boolean(1),
    following: Boolean(1),
    verified: Boolean(0),
    promoted: Boolean(1),
  },
  {
    name: 'Marjorie',
    username: 'Mosciski',
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1001.jpg',
    follower: Boolean(1),
    following: Boolean(0),
    verified: Boolean(0),
    promoted: Boolean(0),
  },
  {
    name: 'Annamarie',
    username: 'Gottlieb',
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/882.jpg',
    follower: Boolean(0),
    following: Boolean(1),
    verified: Boolean(1),
    promoted: Boolean(0),
  },
  {
    name: 'Violette',
    username: 'Schumm',
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/417.jpg',
    follower: Boolean(0),
    following: Boolean(0),
    verified: Boolean(1),
    promoted: Boolean(1),
  },
  {
    name: 'Theo',
    username: 'Stamm',
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/203.jpg',
    follower: Boolean(1),
    following: Boolean(1),
    verified: Boolean(0),
    promoted: Boolean(1),
  },
  {
    name: 'Yasmin',
    username: 'Wyman',
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/120.jpg',
    follower: Boolean(1),
    following: Boolean(1),
    verified: Boolean(0),
    promoted: Boolean(0),
  },
  {
    name: 'Greta',
    username: 'Greenholt',
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1092.jpg',
    follower: Boolean(1),
    following: Boolean(0),
    verified: Boolean(1),
    promoted: Boolean(1),
  },
  {
    name: 'Kiel',
    username: 'Fritsch',
    img: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/663.jpg',
    follower: Boolean(0),
    following: Boolean(0),
    verified: Boolean(1),
    promoted: Boolean(1),
  },
];

export const WHAT_HAPPENING = [
  {
    topic: 'Tasty Wooden Computer',
    title: 'Pants',
    amount: 31.2,
  },
  {
    topic: 'Licensed Steel Fish',
    title: 'Chips',
    amount: 22.5,
  },
  {
    topic: 'Unbranded Fresh Bacon',
    title: 'Shirt',
    amount: 23.3,
  },
  {
    topic: 'Rustic Granite Bacon',
    title: 'Salad',
    amount: 58.7,
  },
  {
    topic: 'Generic Metal Shirt',
    title: 'Computer',
    amount: 62.7,
  },
  {
    topic: 'Refined Fresh Chair',
    title: 'Towels',
    amount: 24.0,
  },
  {
    topic: 'Sleek Fresh Shirt',
    title: 'Tuna',
    amount: 97.9,
  },
  {
    topic: 'Sleek Soft Soap',
    title: 'Bacon',
    amount: 7.2,
  },
  {
    topic: 'Rustic Concrete Cheese',
    title: 'Soap',
    amount: 28.3,
  },
  {
    topic: 'Incredible Soft Chicken',
    title: 'Towels',
    amount: 43.0,
  },
];

export const USER_TWEETS = [
  {
    content:
      'Molestiae sit velit delectus necessitatibus autem. Et ducimus odit. Rerum harum quam consequatur sit eligendi. Eum ea quo repudiandae eos delectus ipsum. Id deleniti magni qui in neque est minima recusandae.',
    comments: 37,
    retweets: 48,
    likes: 88,
  },
  {
    content:
      'Porro hic iusto quisquam molestiae quos aperiam. Et voluptates eum quaerat. Ut velit corrupti aut atque. Ad reprehenderit voluptatem aut est. Quia consequatur officiis laborum. Qui saepe nihil perspiciatis quidem assumenda labore sed numquam.',
    comments: 85,
    retweets: 19,
    likes: 49,
  },
  {
    content: 'Vel tenetur rerum. Sit nisi porro. Labore nostrum voluptas consectetur nihil.',
    comments: 23,
    retweets: 88,
    likes: 91,
  },
  {
    content:
      'Iusto eligendi in totam quia velit alias dicta aliquid sit. Maiores at quia eum eaque quia. Non et aliquid adipisci occaecati. Distinctio sunt ad laborum deleniti ipsum doloribus id rerum magnam.',
    comments: 97,
    retweets: 17,
    likes: 3,
  },
  {
    content:
      'Optio sequi sed et necessitatibus. Tenetur ea fuga ad libero magni aperiam pariatur quas.',
    comments: 83,
    retweets: 97,
    likes: 9,
  },
  {
    content:
      'Et similique ducimus consequuntur. Qui mollitia accusantium quo. Odio eveniet totam modi. Eveniet velit eos perspiciatis ullam veniam mollitia eius.',
    comments: 94,
    retweets: 32,
    likes: 55,
  },
  {
    content:
      'Ipsam voluptatum recusandae optio vero repudiandae et adipisci voluptatem consequatur. Ut veniam aut autem ex et alias. Aliquid sed ipsa dolorem culpa natus incidunt repellendus ipsam sequi. Voluptatibus omnis dolore voluptatem accusantium id atque temporibus ut. Consequatur dolorum fugit quo iste.',
    comments: 63,
    retweets: 5,
    likes: 21,
  },
  {
    content:
      'Non dolores optio. Dolore sit recusandae ipsam non dicta et. Voluptas unde soluta aliquid perferendis unde ipsam maxime laborum. Ipsa nam tempore doloribus sunt ab molestias debitis ut. Quo ipsum suscipit occaecati qui nostrum quisquam.',
    comments: 27,
    retweets: 37,
    likes: 16,
  },
  {
    content:
      'Sit facere et neque ipsa quod consequuntur. Sequi hic molestias reiciendis quisquam ut eaque aut ad.',
    comments: 28,
    retweets: 94,
    likes: 97,
  },
  {
    content:
      'Voluptates tempora eligendi unde voluptas esse aperiam voluptas. Rerum provident reprehenderit quod nam optio corrupti similique voluptas alias. Consequuntur maiores repellendus similique quaerat. Quae ratione facilis. Culpa exercitationem id.',
    comments: 27,
    retweets: 38,
    likes: 47,
  },
];
