# This is a basic workflow to help you get started with Actions

name: Stauts Counter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * FRI'

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
  TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
  ZINNS_TELEGRAM_CHAT_ID: ${{secrets.ZINNS_TELEGRAM_CHAT_ID}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  status-counter:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Status Counter
        run: |
          npm i
          npm run status_counter
